mono: none
dist: trusty

matrix:
  include:
    - language: csharp
      
      dotnet: 3.1
      before_script:
        - cd src/backend
        - dotnet restore solution-name.sln
      script:
        - dotnet build solution-name.sln
        - dotnet test solution-name.sln

    - language: node_js
      node_js:
        - 12.4.0
      before_install:
        - cd src/frontend
      install:
        - npm install
      script:
        - yarn test
