matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1
      dist: xenial
      env:
        - SOLUTION_FILE=src/RejectItDemo.sln
      install:
        - dotnet restore $PROJECT_PATH
      script:
        - dotnet build $PROJECT_PATH
        - dotnet test $PROJECT_PATH

    - language: node_js
      mono: none
      node_js:
        - 12.4.0
      before_install:
        - cd src/RejectItDemo/ClientApp
      install:
        - npm install
      script:
        - npm set progress=false
        - npm run build
        - npm run lint
        - npm run test-headless-ci-only
