mono: none
dist: trusty

matrix:
  include:
    - language: csharp
      
      dotnet: 3.1
      before_script:
        - cd src/backend
        - dotnet restore RejectItDemo.sln
      script:
        - dotnet build RejectItDemo.sln
        - dotnet test RejectItDemo.sln

    - language: node_js
      node_js:
        - 12.4.0
      before_install:
        - cd src/RejectItDemo/ClientApp
      install:
        - npm install
      script:
        - npm lint
        - npm test-headless-ci-only
