mono: none
dist: trusty

matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1.1
      install:
        - dotnet restore
      before_script:
        - cd src
        - dotnet restore RejectItDemo.sln
      script:
        - dotnet build RejectItDemo.sln
        - dotnet test RejectItDemo.sln

    - language: node_js
      mono: none
      node_js:
        - 12.4.0
      before_install:
        - cd src/RejectItDemo/ClientApp
      install:
        - npm install
      script:
        - npm set progress=false
        - npm run build
        - npm run lint
        - npm run test-headless-ci-only
